name: Build & Code Quality Checks

on:
  pull_request:
    branches: ['main', 'hotfix/*']
    types: ['opened', 'reopened', 'synchronize']
  push:
    branches: ['main', 'hotfix/*']

jobs:
  build:
    name: Build & Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        env:
          HUSKY: 0
        run: |
          npm ci

      - name: Execute quality checks
        run: |
          npm run check:circular
          npm run check:duplicates

      - name: Execute security checks
        run: |
          npm run check:security

      # size check only supports PR workflows
      # does github action support an if statement like thing???
      # maybe trigger multiple jobs with if statement check

      # - name: Execute bundle size checks
      #   uses: rudderlabs/github-action-check-size-limit@v2.6.0
      #   env:
      #     HUSKY: 0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     build_script: check:size:build
