name: Deploy Beta Feature

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'beta[0-9]+.[0-9]+.[0-9]+'

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: read # This is required for actions/checkout

jobs:
  deploy-tag:
    name: Deploy beta tag
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_PROD_ACCOUNT_ID }}:role/${{ secrets.AWS_PROD_S3_SYNC_ROLE }}
          aws-region: us-east-1

      - name: Checkout source branch
        uses: actions/checkout@v4

      - name: Get tag name
        run: |
          echo "TAGNAME=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "DATE=$(date)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Build and sync files to S3
        env:
          HUSKY: 0
          BUGSNAG_API_KEY: ${{ secrets.RS_PROD_BUGSNAG_API_KEY }}
          BUGSNAG_RELEASE_STAGE: 'beta'
        # for now, skip integrations
        # npm run build:integration:all
        run: |
          npm ci
          npm run build:browser

      - name: Sync files to S3 beta folder
        # for now, skip integrations
        # aws s3 cp dist/legacy/js-integrations/ s3://${{ secrets.AWS_PROD_S3_BUCKET_NAME }}/beta/${{ env.TAGNAME }}/js-integrations/ --recursive --cache-control max-age=3600
        run: |
          aws s3 cp dist/legacy/events.min.js s3://${{ secrets.AWS_PROD_S3_BUCKET_NAME }}/beta/${{ env.TAGNAME }}/events.min.js --cache-control max-age=3600
          aws s3 cp dist/legacy/events.min.js.map s3://${{ secrets.AWS_PROD_S3_BUCKET_NAME }}/beta/${{ env.TAGNAME }}/events.min.js.map --cache-control max-age=3600
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_PROD_CF_DISTRIBUTION_ID }} --paths "/beta/${{ env.TAGNAME }}/*"
